@token = {{auth.response.body.$.tokenJWT}}

# @name  auth
POST http://localhost:8080/authenticate

{
    "username":"jose@gmail.com",
    "password":"1234"
}
###

GET http://localhost:8080/clientes/1
Authorization: Bearer {{token}}
###


POST http://localhost:8080/clientes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "telefone":"blabla",
    "email":"blabla",
    "senha":"blabla"
}

###



GET http://localhost:8080/profissionais
Authorization: Bearer {{token}}
###


GET http://localhost:8080/profissionais/1
Authorization: Bearer {{token}}
###

POST http://localhost:8080/profissionais
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome":"blabla",
    "telefone":"blabla",
    "email":"blabla",
    "senha":"blabla"
}

###

GET http://localhost:8080/servicos
Authorization: Bearer {{token}}
Content-Type: application/json
###

PUT http://localhost:8080/profissionais/1/servicos
Authorization: Bearer {{token}}
Content-Type: application/json

{"servicos":[1,2,3]}

###


GET http://localhost:8080/saloes
Authorization: Bearer {{token}}
Content-Type: application/json
###

GET http://localhost:8080/saloes/3
Authorization: Bearer {{token}}
Content-Type: application/json
###


PUT http://localhost:8080/profissionais/1/saloes
Authorization: Bearer {{token}}
Content-Type: application/json

{"saloes":[1,2]}
###


GET http://localhost:8080/agendamentos
Authorization: Bearer {{token}}
Content-Type: application/json


